{
 "title": "Used | Wasted Resources",
 "description": "Dashboard to show the resource requests vs allocatable in the cluster",
 "tags": [
  "kubernetes",
  "k8s",
  "prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_namespace_created, namespace)"
    }
   },
   {
    "name": "app",
    "label": "app",
    "query": {
     "query": "label_values(kube_deployment_labels{namespace=\"$namespace\"}, deployment)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(kube_node_info, node)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster Wide", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "This represents the total [memory resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-memory) in the cluster.\nFor comparison the total [allocatable memory](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "expr": "min(sum(kube_node_status_allocatable{resource=\"memory\"} / 1024 ) by (instance))",
     "legendFormat": "Allocatable Memory"
    },
    {
     "expr": "sum(\nsum(kube_pod_container_resource_requests{resource=\"memory\"} / 1024 ) by (pod)\n * on (pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\"}) by (pod) == 1)\n )",
     "legendFormat": "Requested Memory"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{node=~\"$instance\", container!=\"POD\", container!=\"\"}) / 1024",
     "legendFormat": "Used Memory"
    },
    {
     "expr": "sum(\nsum(kube_pod_container_resource_limits{resource=\"memory\"} / 1024 ) by (pod)\n * on (pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\"}) by (pod) == 1)\n )",
     "legendFormat": "Memory Limits"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\nsum(kube_pod_container_resource_requests{resource=\"memory\"}) by (pod)\n * on (pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\"}) by (pod) == 1)\n ) / min(sum(kube_node_status_allocatable{resource=\"memory\"}) by (instance)) * 100"
    }
   ]
  },
  {
   "title": "Allocatable Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{node=~\"$instance\", container!=\"POD\", container!=\"\"})"
    }
   ]
  },
  {
   "title": "Wasted CPU %",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (sum(rate(container_cpu_usage_seconds_total{image!=\"\", container_name!=\"POD\", instance=~\"$instance\"}[5m])) /\nsum(\nsum(kube_pod_container_resource_requests{resource=\"cpu\", instance=~\"$instance\"}) by (pod, instance)\n * on (pod, instance) group_left()  (sum(kube_pod_status_phase{phase=\"Running\", instance=~\"$instance\"}) by (pod, instance) == 1)\n ) * 100)"
    }
   ]
  },
  {
   "title": "Wasted RAM %",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (sum(container_memory_working_set_bytes{instance=~\"$instance\",container!=\"POD\", container!=\"\"}) / sum(kube_pod_container_resource_requests{instance=~\"$instance\", unit=\"byte\", container!=\"\"}) * 100)"
    }
   ]
  },
  {
   "title": "Requested Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\nsum(kube_pod_container_resource_requests{resource=\"memory\"}) by (pod)\n * on (pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\"}) by (pod) == 1)\n )"
    }
   ]
  },
  {
   "title": "Wasted CPU  % without kubesystem",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 5, "x": 13, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (sum(rate(container_cpu_usage_seconds_total{image!=\"\", container_name!=\"POD\", instance=~\"$instance\", namespace!=\"kube-system\"}[5m])) /\nsum(\nsum(kube_pod_container_resource_requests{resource=\"cpu\", instance=~\"$instance\", namespace!=\"kube-system\"}) by (pod, instance)\n * on (pod, instance) group_left()  (sum(kube_pod_status_phase{phase=\"Running\", instance=~\"$instance\", namespace!=\"kube-system\"}) by (pod, instance) == 1)\n ) * 100)"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "timeseries",
   "description": "This represents the total [CPU resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-cpu) in the cluster.\nFor comparison the total [allocatable CPU cores](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\nsum(kube_pod_container_resource_requests{resource=\"cpu\"}) by (pod)\n * on (pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\"}) by (pod) == 1)\n )",
     "legendFormat": "Requested CPU Cores"
    },
    {
     "expr": "sum(kube_node_status_allocatable{unit=\"core\"})",
     "legendFormat": "Allocatable CPU Cores"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\", container!=\"POD\", container!=\"\"}[5m]))",
     "legendFormat": "Used CPU Cores"
    },
    {
     "expr": "sum(\nsum(kube_pod_container_resource_limits{resource=\"cpu\"}) by (pod)\n * on (pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\"}) by (pod) == 1)\n )",
     "legendFormat": "CPU Limits"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 7, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(\nsum(kube_pod_container_resource_requests{resource=\"cpu\"}) by (pod)\n * on (pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\"}) by (pod) == 1)\n )\n / min(sum(kube_node_status_allocatable{unit=\"core\"}) by (instance)) * 100"
    }
   ]
  },
  {
   "title": "Allocatable CPU Cores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{unit=\"core\"})"
    }
   ]
  },
  {
   "title": "Wasted RAM % without kube-system",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 5, "x": 13, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (sum(container_memory_working_set_bytes{instance=~\"$instance\",container!=\"POD\", container!=\"\", namespace!=\"kube-system\"}) / sum(kube_pod_container_resource_requests{instance=~\"$instance\", unit=\"byte\", container!=\"\", namespace!=\"kube-system\"}) * 100)"
    }
   ]
  },
  {
   "title": "Wasted CPU by Namespace %",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (sum(rate(container_cpu_usage_seconds_total{image!=\"\", container_name!=\"POD\", namespace=~\"$namespace\"}[5m])) /\nsum(\nsum(kube_pod_container_resource_requests{resource=\"cpu\", namespace=~\"$namespace\"}) by (pod, namespace)\n * on (pod, namespace) group_left()  (sum(kube_pod_status_phase{phase=\"Running\", namespace=~\"$namespace\"}) by (pod, namespace) == 1)\n ) * 100)"
    }
   ]
  },
  {
   "title": "Wasted RAM by Namespace %",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (sum(container_memory_working_set_bytes{instance=~\"$instance\",container!=\"POD\", container!=\"\", namespace=\"$namespace\"}) / sum(kube_pod_container_resource_requests{instance=~\"$instance\", unit=\"byte\", container!=\"\", namespace=\"$namespace\"}) * 100)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Requested CPU Cores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\nsum(kube_pod_container_resource_requests{resource=\"cpu\"}) by (pod)\n * on (pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\"}) by (pod) == 1)\n )"
    }
   ]
  },
  {
   "title": "Used CPU Cores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\", container!=\"POD\", container!=\"\"}[5m]))"
    }
   ]
  },
  {
   "title": "Requests/Limit/Usage by Namespace",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\nsum(kube_pod_container_resource_requests{namespace=~\".*\", resource=\"memory\"}) by (namespace, pod)\n * on (namespace, pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\", namespace=~\".*\"}) by (namespace, pod) == 1)\n ) by (namespace)",
     "legendFormat": "Requested Memory"
    },
    {
     "expr": "sum(\nsum(kube_pod_container_resource_limits{namespace=~\".*\", resource=\"memory\"}) by (namespace, pod)\n * on (namespace, pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\", namespace=~\".*\"}) by (namespace, pod) == 1)\n ) by (namespace)",
     "legendFormat": "Limit Memory"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{node=~\"$instance\", container!=\"POD\", container!=\"\"}) by (namespace)",
     "legendFormat": "Used Memory"
    },
    {
     "expr": "sum(\nsum(kube_pod_container_resource_requests{namespace=~\".*\", resource=\"cpu\"}) by (namespace, pod)\n * on (namespace, pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\", namespace=~\".*\"}) by (namespace, pod) == 1)\n ) by (namespace)",
     "legendFormat": "Requested CPU"
    },
    {
     "expr": "sum(\nsum(kube_pod_container_resource_limits{namespace=~\".*\", resource=\"cpu\"}) by (namespace, pod)\n * on (namespace, pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\"}) by (namespace, pod) == 1)\n ) by (namespace)",
     "legendFormat": "Limit CPU"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\", container_name!=\"POD\"}[5m]))",
     "legendFormat": "Used CPU"
    }
   ]
  },
  {
   "title": "Resource by Namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory",
     "type": "timeseries",
     "description": "This represents the total [memory resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-memory) in the cluster.\nFor comparison the total [allocatable memory](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 131 },
     "fieldConfig": { "defaults": { "unit": "kbytes" } },
     "targets": [
      {
       "expr": "sum(\nsum(kube_pod_container_resource_requests{node=~\"$instance\", namespace=\"$namespace\", resource=\"memory\"}) by (pod)\n * on (pod) group_left()  (sum(kube_pod_status_phase{node=~\"$instance\", phase=\"Running\", namespace=\"$namespace\"}) by (pod) == 1)\n ) / 1000",
       "legendFormat": "Requested Memory"
      },
      {
       "expr": "sum(\nsum(kube_pod_container_resource_limits{node=~\"$instance\", namespace=\"$namespace\", resource=\"memory\"}) by (pod)\n * on (pod) group_left()  (sum(kube_pod_status_phase{node=~\"$instance\", phase=\"Running\", namespace=\"$namespace\"}) by (pod) == 1)\n ) / 1000",
       "legendFormat": "Limit Memory"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{node=~\"$instance\", container!=\"POD\", container!=\"\", namespace=\"$namespace\"}) / 1000",
       "legendFormat": "Used Memory"
      }
     ]
    },
    {
     "title": "Allocatable Memory",
     "type": "stat",
     "gridPos": { "h": 9, "w": 4, "x": 12, "y": 131 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\nsum(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\"}) by (pod)\n * on (pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\", namespace=\"$namespace\"}) by (pod) == 1)\n )"
      }
     ]
    },
    {
     "title": "Limit Memory",
     "type": "stat",
     "gridPos": { "h": 9, "w": 4, "x": 16, "y": 131 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\nsum(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"memory\"}) by (pod)\n * on (pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\", namespace=\"$namespace\"}) by (pod) == 1)\n )"
      }
     ]
    },
    {
     "title": "Used Memory",
     "type": "stat",
     "gridPos": { "h": 9, "w": 4, "x": 20, "y": 131 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{node=~\"$instance\", namespace=\"$namespace\", name!=\"\"})"
      }
     ]
    },
    {
     "title": "CPU Cores",
     "type": "timeseries",
     "description": "This represents the total [CPU resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-cpu) in the cluster.\nFor comparison the total [allocatable CPU cores](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 188 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(\nsum(kube_pod_container_resource_requests{instance=~\"$instance\",namespace=\"$namespace\", resource=\"cpu\"}) by (pod)\n * on (pod) group_left()  (sum(kube_pod_status_phase{instance=~\"$instance\",phase=\"Running\", namespace=\"$namespace\"}) by (pod) == 1)\n )",
       "legendFormat": "Requested CPU"
      },
      {
       "expr": "sum(\nsum(kube_pod_container_resource_limits{instance=~\"$instance\",namespace=\"$namespace\", resource=\"cpu\"}) by (pod)\n * on (pod) group_left()  (sum(kube_pod_status_phase{instance=~\"$instance\",phase=\"Running\", namespace=\"$namespace\"}) by (pod) == 1)\n )",
       "legendFormat": "Limit CPU"
      },
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{instance=~\"$instance\",image!=\"\", container!=\"POD\", container!=\"\", namespace=~\"$namespace\"}[5m]))",
       "legendFormat": "CPU Usage"
      }
     ]
    },
    {
     "title": "Allocatable CPU Cores",
     "type": "stat",
     "gridPos": { "h": 9, "w": 4, "x": 12, "y": 188 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\nsum(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"cpu\"}) by (pod)\n * on (pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\", namespace=\"$namespace\"}) by (pod) == 1)\n )"
      }
     ]
    },
    {
     "title": "Limit CPU Cores",
     "type": "stat",
     "gridPos": { "h": 9, "w": 4, "x": 16, "y": 188 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\nsum(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"cpu\"}) by (pod)\n * on (pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\", namespace=\"$namespace\"}) by (pod) == 1)\n )"
      }
     ]
    },
    {
     "title": "Used CPU Cores",
     "type": "stat",
     "gridPos": { "h": 9, "w": 4, "x": 20, "y": 188 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\", container_name!=\"POD\", namespace=~\"$namespace\"}[5m]))"
      }
     ]
    },
    {
     "title": "Memory Request/Limit by Pod",
     "type": "table",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 197 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\"}) by (pod)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"memory\"})  by (pod)"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{node=~\"$instance\", container!=\"POD\", container!=\"\", namespace=\"$namespace\"}) by (pod) ",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(avg_over_time(node_namespace_pod_container:container_memory_working_set_bytes{namespace=~\"$namespace\",pod=~\".*\"}[1d])) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Request/Limit by Pod",
     "type": "table",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 197 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", namespace=~\"$namespace\"}) by (pod)* on (pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\"}) by (pod) == 1)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", namespace=~\"$namespace\"}) by (pod) * on (pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\"}) by (pod) == 1)"
      },
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{instance=~\"$instance\",image!=\"\", container!=\"POD\", container!=\"\", namespace=~\"$namespace\"}[5m])) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource by app",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory by pod",
     "type": "timeseries",
     "description": "This represents the total [memory resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-memory) in the cluster.\nFor comparison the total [allocatable memory](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "kbytes" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\", container!=\"POD\", container!=\"\"}) by (pod) / 1024",
       "legendFormat": "Requested Memory {{pod}}"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"memory\", container!=\"POD\", container!=\"\"})  by (pod) / 1024",
       "legendFormat": "Limit Memory {{pod}}"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"POD\", container!=\"\"})  by (pod) / 1024",
       "legendFormat": "Used Memory {{pod}}"
      }
     ]
    },
    {
     "title": "CPU Cores by pod",
     "type": "timeseries",
     "description": "This represents the total [CPU resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-cpu) in the cluster.\nFor comparison the total [allocatable CPU cores](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"$namespace\", container!=\"POD\", container!=\"\"}) by (pod)",
       "legendFormat": "Requested CPU {{pod}}"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"$namespace\", container!=\"POD\", container!=\"\"}) by (pod)",
       "legendFormat": "Limit CPU {{pod}}"
      },
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",  container!=\"POD\", container!=\"\"}[5m])) by (pod)",
       "legendFormat": "Used CPU {{pod}}"
      }
     ]
    },
    {
     "title": "Memory Request/Limit by Pod",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 112 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\",pod=~\".*\"}) by (pod, container)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"memory\", container!=\"POD\", container!=\"\"})  by (pod, container)"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace\", container!=\"POD\", container!=\"\"}) by (pod, container)"
      },
      {
       "expr": "sum(avg_over_time(node_namespace_pod_container:container_memory_working_set_bytes{namespace=~\"$namespace\", container!=\"POD\", container!=\"\"}[1d])) by (pod, container)"
      },
      {
       "expr": "sum(max_over_time(node_namespace_pod_container:container_memory_working_set_bytes{namespace=~\"$namespace\", container!=\"POD\", container!=\"\"}[1d])) by (pod, container)"
      }
     ]
    },
    {
     "title": "CPU Request/Limit by Pod",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 121 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"$namespace\",container!=\"POD\", container!=\"\"}) by (pod, container)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"$namespace\",container!=\"POD\", container!=\"\"}) by (pod, container)"
      },
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"POD\", container!=\"\"}[5m])) by (pod, container)"
      },
      {
       "expr": "sum(avg_over_time(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~\"$namespace\",container!=\"POD\", container!=\"\"}[1d])) by (pod, container)"
      },
      {
       "expr": "sum(max_over_time(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~\"$namespace\",container!=\"POD\", container!=\"\"}[1d])) by (pod, container)"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource by Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nodes Allocatable vs Usage",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(kube_node_status_allocatable{resource=\"memory\"}) by (node)"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{node=~\"$instance\", container!=\"POD\", container!=\"\"}) by (node)"
      }
     ]
    },
    {
     "title": "CPU Allocatable vs Usage",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(kube_node_status_allocatable{resource=\"cpu\"}) by (node)"
      },
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\", container!=\"POD\", container!=\"\"}[5m])) by (node)"
      }
     ]
    },
    {
     "title": "CPU / Memory Allocatable vs Utilization",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(kube_node_status_allocatable{resource=\"memory\", node=~\"$instance\"}) by (node)",
       "legendFormat": "Memory Allocatable: {{node}}"
      },
      {
       "expr": "sum(kube_metrics_server_nodes_mem{exported_instance=~\"$instance\"}) by (exported_instance) * 1024",
       "legendFormat": "Memory Utilization: {{exported_instance}}"
      },
      {
       "expr": "sum(kube_node_status_allocatable{resource=\"cpu\", node=~\"$instance\"}) by (node)",
       "legendFormat": "CPU Allocatable: {{node}}"
      },
      {
       "expr": "sum(kube_metrics_server_nodes_cpu{exported_instance=~\"$instance\"}) by (exported_instance) / 1000000000 ",
       "legendFormat": "CPU Utilization: {{exported_instance}}"
      }
     ]
    }
   ]
  }
 ]
}